In [1]:
import pandas as pd
data = pd.read_csv('../../DiffTasks_subject/Subjects.csv')
difftasks_subs = pd.read_csv('qc/sessions4toolbox.csv')['UID']
data_difftasks = data[data['Subjects::UniqueID'].isin(difftasks_subs)]
data_difftasks = data_difftasks[data_difftasks['Experiment'].str.contains('DiffTasks')]
data_difftasks = data_difftasks.drop_duplicates(subset='Subjects::UniqueID', keep='last')
data_difftasks = data_difftasks.sort_values(by='Subjects::UniqueID')

In [2]:
data_difftasks.columns

Index(['Experiment', 'ExperimentType', 'Subjects::UniqueID', 'Subjects::PKey',
       'ScanSessions::SessionID', 'ScanSessions::Date',
       'ScanSessions::Scanner', 'NumRuns', 'ScanSessions::AgeAtSession',
       'Subjects::Gender', 'Subjects::Handedness', 'Subjects::NativeEnglish',
       'Subjects::Ethnicity', 'ScanSessions::Second',
       'ScanSessions::Experimenter', 'Subjects::IncidentalFinding'],
      dtype='object')

In [3]:
data_difftasks['Subjects::Gender'].value_counts(), \
    data_difftasks['Subjects::Handedness'].value_counts(), \
    data_difftasks['Subjects::NativeEnglish'].value_counts(), \
    data_difftasks['ScanSessions::AgeAtSession'].describe()

(Subjects::Gender
 F    31
 M    21
 Name: count, dtype: int64,
 Subjects::Handedness
 right    42
 left      1
 Name: count, dtype: int64,
 Subjects::NativeEnglish
 1    33
 0    10
 Name: count, dtype: int64,
 count    52.000000
 mean     23.884615
 std       3.786736
 min      18.000000
 25%      21.000000
 50%      23.000000
 75%      26.000000
 max      34.000000
 Name: ScanSessions::AgeAtSession, dtype: float64)

In [4]:
data_difftasks[['ScanSessions::Date', 'Subjects::UniqueID', 'Subjects::Handedness', 'Subjects::Gender', 'Subjects::NativeEnglish', 'ScanSessions::AgeAtSession']]

,ScanSessions::Date,Subjects::UniqueID,Subjects::Handedness,Subjects::Gender,Subjects::NativeEnglish,ScanSessions::AgeAtSession
1842,03/22/2017,212.0,right,M,1,22.0
1845,04/17/2017,249.0,right,M,1,20.0
1903,01/23/2019,338.0,right,F,1,28.0
1846,04/17/2017,365.0,right,F,0,20.0
1853,07/27/2017,382.0,right,F,1,29.0
1841,03/21/2017,426.0,right,M,1,32.0
1847,04/20/2017,551.0,right,F,1,28.0
1848,04/28/2017,553.0,right,M,1,19.0
1916,02/08/2019,584.0,right,F,1,20.0
1849,05/01/2017,602.0,right,M,1,23.0
1850,05/02/2017,604.0,right,F,1,19.0
1851,05/05/2017,605.0,right,F,1,22.0
1852,05/15/2017,606.0,right,M,0,24.0
1941,07/20/2018,673.0,right,F,1,25.0
1942,07/20/2018,674.0,right,M,0,24.0
1943,07/26/2018,675.0,right,F,1,24.0
1912,01/31/2019,680.0,right,F,1,25.0
1900,01/17/2019,705.0,right,F,0,18.0
1902,01/17/2019,707.0,right,F,1,20.0
1904,01/24/2019,709.0,right,F,1,22.0
1905,01/24/2019,710.0,right,F,0,29.0
1906,01/24/2019,711.0,right,F,0,29.0
1907,01/24/2019,712.0,right,F,0,28.0
1908,01/31/2019,714.0,right,M,0,26.0
1909,01/31/2019,715.0,right,F,1,21.0
1911,01/31/2019,716.0,right,F,0,27.0
1913,02/07/2019,717.0,right,M,1,24.0
1914,02/07/2019,718.0,right,F,0,26.0
1915,02/07/2019,719.0,right,M,1,27.0
1917,02/08/2019,720.0,right,M,1,23.0
1919,02/13/2019,722.0,right,F,1,21.0
1921,02/14/2019,724.0,right,F,1,26.0
1951,09/02/2021,820.0,right,M,1,25.0
1956,09/29/2021,837.0,right,F,1,22.0
1950,09/02/2021,838.0,NaN,M,NaN,19.0
1944,08/12/2021,839.0,right,M,1,30.0
1945,08/12/2021,840.0,right,F,1,22.0
1946,08/13/2021,841.0,left,M,1,22.0
1947,08/13/2021,842.0,right,M,1,22.0
1948,09/02/2021,843.0,NaN,F,NaN,22.0
1949,09/02/2021,844.0,NaN,F,NaN,19.0
1954,09/22/2021,845.0,NaN,F,NaN,24.0
1955,09/22/2021,846.0,NaN,M,NaN,34.0
1952,09/22/2021,847.0,NaN,F,NaN,23.0
1953,09/22/2021,848.0,right,F,1,22.0
1958,09/29/2021,849.0,NaN,F,NaN,21.0
1959,09/29/2021,850.0,NaN,F,NaN,26.0
1957,09/29/2021,851.0,NaN,M,NaN,26.0
1963,02/09/2022,856.0,right,M,1,31.0
1960,02/03/2022,864.0,right,M,1,18.0
1961,02/07/2022,865.0,right,F,1,20.0
1962,02/09/2022,866.0,right,M,1,23.0

In [5]:
selected = data_difftasks[['ScanSessions::SessionID', 'ScanSessions::Date', 'Subjects::UniqueID', 'Subjects::Handedness', 'Subjects::Gender', 'Subjects::NativeEnglish', 'ScanSessions::AgeAtSession']].reset_index(drop=True)
selected['Subjects::UniqueID'] = selected['Subjects::UniqueID'].astype(int).astype(str)
selected.to_csv('demographics.csv', index=False)
selected = selected[selected['Subjects::NativeEnglish'].astype(str) != '1']
selected

,ScanSessions::SessionID,ScanSessions::Date,Subjects::UniqueID,Subjects::Handedness,Subjects::Gender,Subjects::NativeEnglish,ScanSessions::AgeAtSession
3,FED_20170417c_3T2,04/17/2017,365,right,F,0,20.0
12,FED_20170515a_3T2,05/15/2017,606,right,M,0,24.0
14,FED_20180720b_3T2,07/20/2018,674,right,M,0,24.0
17,FED_20190117a_3T2,01/17/2019,705,right,F,0,18.0
20,FED_20190124b_3T2,01/24/2019,710,right,F,0,29.0
21,FED_20190124c_3T2,01/24/2019,711,right,F,0,29.0
22,FED_20190124d_3T2,01/24/2019,712,right,F,0,28.0
23,FED_20190131a_3T2,01/31/2019,714,right,M,0,26.0
25,FED_20190131d_3T2,01/31/2019,716,right,F,0,27.0
27,FED_20190207b_3T2,02/07/2019,718,right,F,0,26.0
34,FED_20210902d_3T2,09/02/2021,838,NaN,M,NaN,19.0
39,FED_20210902b_3T2,09/02/2021,843,NaN,F,NaN,22.0
40,FED_20210902c_3T2,09/02/2021,844,NaN,F,NaN,19.0
41,FED_20210922a_3T2,09/22/2021,845,NaN,F,NaN,24.0
42,FED_20210922b_3T2,09/22/2021,846,NaN,M,NaN,34.0
43,FED_20210922c_3T2,09/22/2021,847,NaN,F,NaN,23.0
45,FED_20210929a_3T2,09/29/2021,849,NaN,F,NaN,21.0
46,FED_20210929b_3T2,09/29/2021,850,NaN,F,NaN,26.0
47,FED_20210929d_3T2,09/29/2021,851,NaN,M,NaN,26.0

In [6]:
selected.to_csv('demographics_to_inspect.csv', index=False)