In [4]:
import pandas as pd
data_lh = pd.read_csv('Data/all_data_LH.csv')
data_rh = pd.read_csv('Data/all_data_RH.csv')

In [9]:
# average for each combination of Subject_Type, Task_Type
summary_lh = data_lh.groupby(['Subject_Type', 'Task_Type'])['DC'].mean().reset_index()
summary_rh = data_rh.groupby(['Subject_Type', 'Task_Type'])['DC'].mean().reset_index()

In [10]:
summary_lh

      Subject_Type       Task_Type        DC
0  Between-subject  Different-task  0.125744
1  Between-subject       Same-task  0.127877
2   Within-subject  Different-task  0.499606
3   Within-subject       Same-task  0.586949

In [11]:
summary_rh

      Subject_Type       Task_Type        DC
0  Between-subject  Different-task  0.119272
1  Between-subject       Same-task  0.122201
2   Within-subject  Different-task  0.337126
3   Within-subject       Same-task  0.411770